### ISSUE TITLE
TypeScript Compilation Error - anchor has not exported member 'Wallet'

### ISSUE THREAD

**Issue by joemccann** [drift-labs/example-bots#2]
Steps to repro:

> Note: assume you have a private key in the `.env` file.

```sh
yarn
ts-node src/liquidator-bot.ts
```

```sh
 ⚡︎~/solana/liqudation-bots/drift/ master ts-node src/liquidator-bot.ts
/opt/homebrew/lib/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/liquidator-bot.ts:1:24 - error TS2305: Module '"@project-serum/anchor"' has no exported member 'Wallet'.

1 import { BN, Provider, Wallet } from '@project-serum/anchor';
                         ~~~~~~

    at createTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1322:43)
    at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1454:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Object.require.extensions.<computed> [as .ts] (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  diagnosticCodes: [ 2305 ]
}
```

Node Version: 17.6.0
OS: MacOS 12.2.1

**Comment by crispheaney** [comment]
Fixed here! https://github.com/drift-labs/example-bots/commit/260ff442e60654bcee8f92af24b1d540555d345b
